Repository sanders41/meilisearch-tui, pull requests merged in 2023-04, with the labels that each got.

#11 Update readme
  README.md
Labels: skip-changelog

#12 Update CI linting for pre-commit
  .github/workflows/testing.yaml
  .pre-commit-config.yaml
  meilisearch_tui/screens/search.py
Labels: skip-changelog

#13 Add option to start dev mode with data loaded
  justfile
  scripts/load_data.py
Labels: skip-changelog

#15 Update readme
  README.md
  assets/search.gif
Labels: skip-changelog

#16 Import README image quality
  assets/search.gif
Labels: skip-changelog

#17 Update image path
  README.md
Labels: skip-changelog

#18 Update pyproject.toml file
  pyproject.toml
Labels: skip-changelog

#20 Add CONTRIBUTING file
  CONTRIBUTING.md
  README.md
Labels: skip-changelog

#21 Add test badge
  README.md
Labels: skip-changelog

#24 Bump version for release
  pyproject.toml
Labels: skip-changelog

#25 Add config tests
  .github/workflows/testing.yaml
  tests/conftest.py
  tests/test_config.py
Labels: skip-changelog

#26 Add tests
  .github/workflows/testing.yaml
  meilisearch_tui/__main__.py
  meilisearch_tui/client.py
  meilisearch_tui/config.py
  meilisearch_tui/screens/configuration.py
  meilisearch_tui/screens/index.py
  tests/conftest.py
  tests/test_config.py
  tests/test_utils.py
Labels: skip-changelog

#27 Add MEILI_HTTP_ADDR environment vairable to README
  README.md
Labels: skip-changelog

#30 Add test for client
  tests/test_client.py
Labels: skip-changelog

#31 Remove unused screens and widgets
  meilisearch_tui/screens/index.py
  meilisearch_tui/screens/welcome.py
  meilisearch_tui/widgets/sidebar.py
Labels: skip-changelog

#32 Add more tests for config
  tests/test_config.py
Labels: skip-changelog

#29 Change: snake_case to kebab case
  meilisearch_tui/__main__.py
  meilisearch_tui/screens/configuration.py
  meilisearch_tui/screens/data_load.py
  meilisearch_tui/screens/search.py
  meilisearch_tui/widgets/index.py
Labels: skip-changelog

#37 Fix bug where current index box wasn't updating
  meilisearch_tui/screens/data_load.py
  meilisearch_tui/widgets/index.py
Labels: bug

#38 Bump version for release
  pyproject.toml
Labels: skip-changelog

#39 Update release drafter template
  .github/release_draft_template.yaml
Labels: skip-changelog

#40 Fix typo
  README.md
Labels: skip-changelog

#42 Bump meilisearch-python-async from v1.0.0 to v1.1.0
  poetry.lock
  pyproject.toml
Labels: skip-changelog, dependencies

#43 Prevent save of configs set from environment variables
  meilisearch_tui/config.py
  meilisearch_tui/screens/configuration.py
Labels: bug

#46 Remove extra reference to index
  meilisearch_tui/screens/meilisearch_settings.py
Labels: bug

#50 Remove duplicated scrollbar
  meilisearch_tui/meilisearch.css
Labels: bug

#52 Update readme images
  README.md
  assets/search.gif
  assets/search.mp4
  assets/settings.png
Labels: skip-changelog

#54 Switch movie back to gif
  README.md
  assets/search.gif
  assets/search.mov
Labels: skip-changelog

#55 Bump version for release
  pyproject.toml
Labels: skip-changelog

#58 Refactor node queries into properties
  meilisearch_tui/screens/data_load.py
  meilisearch_tui/screens/meilisearch_settings.py
Labels: skip-changelog

#57 Bump textual from 0.17.3 to 0.18.0 and update for breaking Markdown change
  meilisearch_tui/screens/meilisearch_settings.py
  meilisearch_tui/screens/search.py
  poetry.lock
  pyproject.toml
Labels: skip-changelog, dependencies

#60 Add indexes screen and ability to add indexes without loading data
  meilisearch_tui/__main__.py
  meilisearch_tui/screens/indexes.py
  meilisearch_tui/utils.py
Labels: enhancement

#61 Bump version for release
  pyproject.toml
Labels: skip-changelog

#63 Revert updating sidbar in a task as it caused a race condition
  meilisearch_tui/screens/indexes.py
  meilisearch_tui/screens/meilisearch_settings.py
  meilisearch_tui/screens/search.py
Labels: bug

#64 Bump version for release
  pyproject.toml
Labels: skip-changelog

#69 Add ability to delete indexes
  meilisearch_tui/screens/indexes.py
Labels: enhancement

#70 Remove unused properties
  meilisearch_tui/screens/indexes.py
Labels: skip-changelog

#74 Bump version for release
  pyproject.toml
Labels: skip-changelog

#75 Fix error when starting with no idexes present
  meilisearch_tui/__main__.py
  meilisearch_tui/screens/indexes.py
  pyproject.toml
Labels: bug

#81 Bump textual from 0.18.0 to 0.19.0
  poetry.lock
  pyproject.toml
Labels: skip-changelog, dependencies

#73 Add ability to edit settings
  meilisearch_tui/screens/indexes.py
  meilisearch_tui/utils.py
  tests/test_utils.py
Labels: enhancement

#82 Bump meilisearch-python-async from 1.1.0 to 1.1.1
  poetry.lock
  pyproject.toml
Labels: skip-changelog, dependencies

#84 Bump version for release
  pyproject.toml
Labels: skip-changelog

#85 Add funding link
  .github/FUNDING.yml
Labels: skip-changelog

#87 Bump textual from v0.19.0 to v0.19.1
  poetry.lock
  pyproject.toml
Labels: skip-changelog, dependencies

#90 Bump version for release
  pyproject.toml
Labels: skip-changelog

#93 Add install to just
  justfile
Labels: skip-changelog

#94 Update CONTRIBUTING for new rust module
  CONTRIBUTING.md
Labels: skip-changelog

#96 Refactor rust module naming
  Cargo.toml
  meilisearch_tui/__init__.py
  meilisearch_tui/_meilisearch_tui.pyi
  meilisearch_tui/screens/indexes.py
  meilisearch_tui/screens/search.py
  pyproject.toml
  src/lib.rs
  tests/test_rust_module.py
Labels: skip-changelog

#98 Add CI tests for Mac and Windows where possible
  .github/workflows/testing.yaml
  pyproject.toml
  tests/test_utils.py
Labels: skip-changelog

#101 Rename lookup_word method to search
  meilisearch_tui/screens/search.py
Labels: skip-changelog

#102 Add TTL cache to search
  meilisearch_tui/screens/search.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#103 Bump version for release
  pyproject.toml
Labels: skip-changelog

#108 Bump version for release
  pyproject.toml
Labels: skip-changelog

#111 Bump aiocache from 0.12.0 to 0.12.1
  poetry.lock
  pyproject.toml
Labels: skip-changelog, dependencies
